// <auto-generated />
using AliBabaCodeChallenge.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliBabaCodeChallenge.Domain.Migrations
{
    [DbContext(typeof(AliBabaDbContext))]
    partial class AliBabaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LastName")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactAddressTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactAddressTypeId");

                    b.HasIndex("ContactId");

                    b.ToTable("contactsAddress");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactAddressType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("contactsAddressType");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactPhoneNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<long>("ContactPhoneNumberTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ContactPhoneNumberTypeId");

                    b.ToTable("contactsPhonenNumber");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactPhoneNumberType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("contactsPhoneNumberType");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactAddress", b =>
                {
                    b.HasOne("AliBabaCodeChallenge.Domain.Models.ContactAddressType", "ContactAddressType")
                        .WithMany("ContactAddress")
                        .HasForeignKey("ContactAddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliBabaCodeChallenge.Domain.Models.Contact", "Contact")
                        .WithMany("ContactAddresses")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("ContactAddressType");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactPhoneNumber", b =>
                {
                    b.HasOne("AliBabaCodeChallenge.Domain.Models.Contact", "Contact")
                        .WithMany("ContactPhoneNumbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliBabaCodeChallenge.Domain.Models.ContactPhoneNumberType", "ContactPhoneNumberType")
                        .WithMany("ContactPhoneNumber")
                        .HasForeignKey("ContactPhoneNumberTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("ContactPhoneNumberType");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.Contact", b =>
                {
                    b.Navigation("ContactAddresses");

                    b.Navigation("ContactPhoneNumbers");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactAddressType", b =>
                {
                    b.Navigation("ContactAddress");
                });

            modelBuilder.Entity("AliBabaCodeChallenge.Domain.Models.ContactPhoneNumberType", b =>
                {
                    b.Navigation("ContactPhoneNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
